import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './ui/navigation/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} md:p-4`}>
        <section className="flex flex-col md:flex-row gap-4">
          <NavBar />
          <div className="flex flex-col w-full">{children}</div>
        </section>
      </body>
    </html>
  )
}
